### ISSUE TITLE
匹配到歌词,但不显示

### ISSUE THREAD

**Issue by EX3124** [VictorModi/Lyrics-Getter-Ext#13]
像这种歌词,获取到的歌词 文本是有[]的,但里面不是时间,app不会正常推送歌词
![屏幕截图 2024-10-08 192349](https://github.com/user-attachments/assets/a3d50340-443c-4d9b-9524-654eff176f8c)
![S41008-19241299](https://github.com/user-attachments/assets/97acbe43-5264-4345-95d2-340a935a0a89)
![S41008-19242186](https://github.com/user-attachments/assets/c1f792d2-c5f2-489a-91c6-429e941302ab)

**Comment by VictorModi** [comment]
是否可能墨·状态栏歌词的Hook点丢失或异常，
能否提供更多日志
或者是你使用的是魅族方案...?

**Comment by VictorModi** [comment]
抱歉没有仔细看这篇issue，您可以检查一下 https://github.com/VictorModi/Lyrics-Getter-Ext/blob/main/app/src/main/java/cn/zhaiyifan/lyric/LyricUtils.java 这部分代码是哪一部分出的问题

**Comment by EX3124** [comment]
我看了,在这里,确实匹配到 "[" "]" 里的文字了
![屏幕截图 2024-10-09 213819](https://github.com/user-attachments/assets/450a1266-46c9-4f5d-8728-3dd750b759e3)
我注意到有这样的
![屏幕截图 2024-10-09 213948](https://github.com/user-attachments/assets/f167b2b4-b794-4621-a237-23c9fa0ead52)
这种歌词是 从1分33 到 3分55 吗
