### ISSUE TITLE
歌词滚动时会显示原状态栏

### ISSUE THREAD

**Issue by EX3124** [VictorModi/Lyrics-Getter-Ext#2]
系统:flyme9 安卓11

![屏幕截图 2024-03-26 103300](https://github.com/VictorModi/Lyrics-Getter-Ext/assets/70867298/5584a3e9-ee38-4817-b23b-b442835e3148)

如视频所示,在歌词滚动时会显示原本的状态栏

https://github.com/VictorModi/Lyrics-Getter-Ext/assets/70867298/03118b49-6cae-4f12-9de6-cd6791c74d3a

我的设置过程

https://github.com/VictorModi/Lyrics-Getter-Ext/assets/70867298/6ba090f8-1e9d-4040-adb1-76c01466c0d0

**Comment by EX3124** [comment]
期望的效果(像1.0.7一样平滑的切换歌词)

https://github.com/VictorModi/Lyrics-Getter-Ext/assets/70867298/2f4c4071-342d-4c21-860e-657b661278aa

**Comment by VictorModi** [comment]
我找时间看看是什么问题，最近太忙了

主要是真没想到这个玩意会有人用，本项目定义实际上为自用学习。
